name: Publish

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ./LibraryManagementApp.API/LibraryManagementApp.API.csproj

      - name: Build
        run: dotnet build ./LibraryManagementApp.API/LibraryManagementApp.API.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./LibraryManagementApp.API/LibraryManagementApp.API.csproj --configuration Release --no-build
  
